const express = require('express');
const nodemailer = require('nodemailer');
const Contact = require('../models/Contact'); // Contact model
const router = express.Router();

router.post('/sendEmail', async (req, res) => {
  const { name, email, message } = req.body;

  const transporter = nodemailer.createTransport({
    host: 'smtp-relay.brevo.com',
    port: 2525,
    secure: false,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.PASSWORD
    }
  });

  const mailOptions = {
    from: `"Portfolio Contact" <${process.env.EMAIL}>`,
    replyTo: process.env.MAILS,
    to: email,
    subject: `💼 Portfolio Contact Request from ${name}`,
    text: `New Portfolio Message:\n\nName: ${name}\nEmail: ${email}\nMessage: ${message}`,
    html: `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>New Contact Request</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
          background-color: #f8fafc;
          color: #1e293b;
          margin: 0;
          padding: 0;
        }
        .container {
          max-width: 600px;
          margin: 30px auto;
          background: #ffffff;
          border-radius: 16px;
          overflow: hidden;
          box-shadow: 0 4px 30px rgba(0, 0, 0, 0.02);
          border: 1px solid #e2e8f0;
        }
        .header {
          background: linear-gradient(135deg, #4f46e5 0%, #db2777 100%);
          color: #ffffff;
          padding: 30px 24px;
          text-align: center;
        }
        .header h1 {
          margin: 0;
          font-size: 22px;
          font-weight: 800;
          letter-spacing: -0.025em;
        }
        .header p {
          margin: 6px 0 0 0;
          font-size: 13px;
          opacity: 0.95;
        }
        .content {
          padding: 30px 24px;
        }
        .field-label {
          font-size: 10px;
          font-weight: 750;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          color: #64748b;
          margin-bottom: 5px;
        }
        .field-value {
          font-size: 14px;
          font-weight: 600;
          color: #0f172a;
          margin-bottom: 22px;
        }
        .message-box {
          background-color: #f8fafc;
          border: 1px solid #e2e8f0;
          border-radius: 12px;
          padding: 16px;
          font-size: 14px;
          line-height: 1.6;
          color: #334155;
          white-space: pre-wrap;
          margin-bottom: 24px;
        }
        .footer {
          background-color: #f8fafc;
          padding: 20px;
          text-align: center;
          border-top: 1px solid #f1f5f9;
        }
        .btn {
          display: inline-block;
          background-color: #4f46e5;
          color: #ffffff !important;
          text-decoration: none;
          font-weight: 600;
          font-size: 13px;
          padding: 11px 22px;
          border-radius: 8px;
          box-shadow: 0 4px 12px rgba(79, 70, 229, 0.15);
        }
        .copyright {
          font-size: 11px;
          color: #94a3b8;
          margin-top: 12px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>New Message Received</h1>
          <p>via your Portfolio Contact Form</p>
        </div>
        <div class="content">
          <div class="field-label">Sender Name</div>
          <div class="field-value">${name}</div>
          
          <div class="field-label">Email Address</div>
          <div class="field-value"><a href="mailto:${email}" style="color: #4f46e5; text-decoration: none;">${email}</a></div>
          
          <div class="field-label">Message</div>
          <div class="message-box">${message}</div>
          
          <div style="text-align: center;">
            <a href="mailto:${process.env.MAILS}" class="btn">Reply to Sender</a>
          </div>
        </div>
        <div class="footer">
          <p style="margin: 0; font-size: 12px; color: #64748b;">This email was automatically generated by your portfolio backend.</p>
          <div class="copyright">&copy; ${new Date().getFullYear()} Hariharan Portfolio</div>
        </div>
      </div>
    </body>
    </html>
    `
  };

  const contact = new Contact({ name, email, message });

  try {
    await transporter.sendMail(mailOptions);  // Send email
    await contact.save();  // Save contact in DB
    res.status(200).json({ message: 'Message sent and saved!' });
  } catch (error) {
    console.error('Error:', error);
    res.status(500).json({ message: 'Failed to send or save.' });
  }
});

module.exports = router;
